services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: expenses
      MYSQL_USER: expenseuser
      MYSQL_PASSWORD: expensepassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
